const initData = [
  {
    catId: '1',
    catName: 'Task',
    catImg: require(`../images/shopping-cart-svgrepo-com.svg`),
    createDate: '9/19/2022',
    content: 'Lorem ipsum dolor sit',
    nameInput: 'Some task',
    mode: 'add',
    recordId: 1663524239469.8655,
    modificationDate: ['9/19/2022'],
    archived: true,
  },
  {
    catId: '1',
    catName: 'Task',
    catImg: require(`../images/shopping-cart-svgrepo-com.svg`),
    createDate: '9/19/2022',
    content: 'Lorem ipsum dolor sit',
    nameInput: 'Some task',
    mode: 'add',
    recordId: '166352427247887',
    modificationDate: ['9/17/2022', '9/18/2022'],
    archived: false,
  },
  {
    catId: '1',
    catName: 'Task',
    catImg: require(`../images/shopping-cart-svgrepo-com.svg`),
    createDate: '9/15/2022',
    content: 'Lorem ipsum dolor sit',
    nameInput: 'Some task',
    mode: 'add',
    recordId: 1663524307213,
    modificationDate: ['9/17/2022', '9/18/2022'],
    archived: true,
  },
  {
    catId: '1',
    catName: 'Task',
    catImg: require(`../images/shopping-cart-svgrepo-com.svg`),
    createDate: '9/14/2022',
    content: 'Lorem ipsum dolor sit',
    nameInput: 'Some task',
    mode: 'add',
    recordId: 1663525334145,
    modificationDate: ['9/17/2022', '9/18/2022'],
    archived: true,
  },
  {
    catId: '2',
    catName: 'Random Thought',
    catImg: require(`../images/idea-think-svgrepo-com.svg`),
    createDate: '9/16/2022',
    content: 'Lorem ipsum dolor sit',
    nameInput: 'Some task',
    mode: 'add',
    recordId: 1663525342591,
    modificationDate: [],
    archived: false,
  },
  {
    catId: '4',
    catName: 'Quote',
    catImg: require(`../images/quote-right-svgrepo-com.svg`),
    createDate: '9/17/2022',
    content: 'Lorem ipsum dolor sit',
    nameInput: 'Some task',
    mode: 'add',
    recordId: 1663525348710,
    modificationDate: [],
    archived: false,
  },
  {
    catId: '1',
    catName: 'Task',
    catImg: require(`../images/shopping-cart-svgrepo-com.svg`),
    createDate: '9/18/2022',
    content: 'Lorem ipsum dolor sit',
    nameInput: 'Some task',
    mode: 'add',
    recordId: 1663565816836,
    modificationDate: [],
    archived: false,
  },
  {
    catId: '1',
    catName: 'Task',
    catImg: require(`../images/shopping-cart-svgrepo-com.svg`),
    createDate: '9/18 /2022',
    content: 'Lorem ipsum dolor sit',
    nameInput: 'Some task',
    mode: 'add',
    recordId: 1663565816836454,
    modificationDate: [],
    archived: false,
  },
];
export default initData;
